### ISSUE TITLE
Test Reports

### ISSUE THREAD

**Issue by john9631** [spyder-ide/spyder.vim#5]
17/6/16  Installed with Spyder 3.0.0.dev0

Opens ok.  Escape takes you to command mode.  

**would be nice to have jk option for escape - lack of jk and visible cursor make testing hard** 

a and i take you back correctly (before and after cursor (which isnt showing))
j, k, h and l seem to work properly
0$w seem ok.
u works oO and dd, dw, D, ZZ work
File commands work

Without a visible cursor I can't test it live.  jk would help although I can do that externally to spyder if its not there.

**Comment by Nodd** [comment]
Thank you for your report. I know that the cursor is a problem, I have to create a false one since the cursor in the editor is not visible when it looses focus. With what is implemented already, you should see a bloc cursor when hitting Esc, but it doesn't move when the cursor moves.
This plugin is far from ready, thanks for taking the time to test it anyway !
